title: ZotEye
tagline: Plagiarism detection for Zotero reference libraries
description: >
  A free, open-source Python-based tool for detecting plagiarism in Zotero reference libraries
url: https://abonfiglio73.github.io
baseurl: /zoteye

author:
  name: Andrea Bonfiglio
  
theme: minima

logo: /assets/images/zoteye-logo.png
image: /assets/images/zoteye-screenshot-interface.png

markdown: kramdown

titles_from_headings:
  enabled: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
